name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
    - uses: actions/checkout@v2
    
    # Step to set up Minikube
    - name: Start Minikube
      uses: medyagh/setup-minikube@master
      id: minikube
    - name: Check Minikube Status
      run: |
        minikube status

    # Step to build Docker image inside Minikube's Docker environment
    - name: Build Docker Image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        echo -n "Verifying images:"
        docker images

    # Check if the image is listed in Minikube's Docker environment
    - name: Verify Docker Image in Minikube
      run: |
        eval $(minikube -p minikube docker-env)
        # Retry checking for the image to ensure it is available
        for i in {1..5}; do
          docker images | grep "devopshint/node-app:latest" && exit 0
          echo "Retrying in 3 seconds..."
          sleep 3
        done
        echo "Docker image not found after 5 retries."
        exit 1
    
    # Step to deploy the application to Minikube
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s-node-app.yaml
        kubectl rollout status deployment/nodejs-app
    
    # Step to list services and verify the service is reachable
    - name: Test Service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url

    # Ensure pods are running after deployment
    - name: Verify Pods Are Running
      run: |
        kubectl get pods -A
        kubectl describe pods -l app=nodejs-app -n default

    # Step to ensure the service is available and check its logs
    - name: Check Deployment and Pod Logs
      run: |
        kubectl describe deployment nodejs-app -n default
        kubectl logs -l app=nodejs-app -n default

    # Final check to ensure the service URL is accessible
    - name: Final Service Check
      run: |
        minikube service nodejs-app --url
