name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Set up Minikube
      uses: medyagh/setup-minikube@v1
      with:
        minikube_version: '1.22.0'
    
    - name: Verify Minikube status
      run: minikube status

    - name: Build Docker Image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f Dockerfile -t devopshint/node-app:latest .
        docker images  # Verify Docker image

    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml

    - name: Check Pods Status
      run: kubectl get pods -A

    - name: Test Service URL
      run: |
        minikube service nodejs-app --url
